Repository googleapis/java-bigquerystorage, pull requests merged in 2020-09, with the labels that each got.

#519 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#523 fix: geo type accepted change from bytes to string
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
Labels: api: bigquerystorage, cla: yes

#522 fix:update schema compat check with backend type changes
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibility.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibilityTest.java
Labels: api: bigquerystorage, cla: yes

#524 build(ci): enable auto-release in this repo
  .github/workflows/auto-release.yaml
Labels: api: bigquerystorage, cla: yes

#526 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#527 chore: generate CODEOWNERS from templates
  .repo-metadata.json
Labels: automerge, cla: yes

#528 [CHANGE ME] Re-generated to pick up changes from self.
  .github/CODEOWNERS
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#534 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: cla: yes, context: full

#538 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#546 chore: exclude org.apache.commons:commons-lang3 from renovate-bot updates
  renovate.json
  synth.py
Labels: cla: yes

#548 chore: exclude org.apache.commons:commons-lang3 using ignoreDeps
  renovate.json
Labels: automerge, cla: yes

#564 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#567 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#566 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: bigquerystorage, cla: yes

#572 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#575 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#576 chore(java): use separate autosynth job for README
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#578 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
