Repository googleapis/java-bigquerystorage, pull requests merged in 2020-07, with the labels that each got.

#389 feat: Add two new fields, ignoreUnknownFields in AppendRowsRequest and update_schema in AppendRowsResponse.
  proto-google-cloud-bigquerystorage-v1alpha2/clirr-ignored-differences.xml
  proto-google-cloud-bigquerystorage-v1alpha2/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/Storage.java
  proto-google-cloud-bigquerystorage-v1alpha2/src/main/proto/google/cloud/bigquery/storage/v1alpha2/storage.proto
  synth.metadata
Labels: cla: yes, context: full

#391 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  google-cloud-bigquerystorage/pom.xml
  grpc-google-cloud-bigquerystorage-v1/pom.xml
  grpc-google-cloud-bigquerystorage-v1alpha2/pom.xml
  grpc-google-cloud-bigquerystorage-v1beta2/pom.xml
  pom.xml
  synth.metadata
Labels: automerge, cla: yes, context: full

#395 feat: Added BQSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
  google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
Labels: automerge, cla: yes

#401 chore: correct ignoreunuseddeclared deps xml structure
  pom.xml
Labels: cla: yes

#410 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#402 fix: BQTableSchemaToProtoDescriptor change type mapping
  google-cloud-bigquerystorage/clirr-ignored-differences.xml
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
  google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
Labels: automerge, cla: yes

#416 [CHANGE ME] Re-generated to pick up changes from googleapis.
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/BigQueryReadStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/stub/BigQueryWriteStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryReadStubSettings.java
  synth.metadata
Labels: cla: yes, context: full

#419 Add 'Received Rst Stream' to automatic retry strings
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BigQueryReadClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryReadClientTest.java
Labels: cla: yes

#415 fix: BQTableSchemaToProtobufDescriptor will now only generate lower-cased fieldnames in the protobuf descriptor
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptorTest.java
  google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
Labels: cla: yes

#423 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#428 fix: ProtoSchemaConver's problem when converting fields reference same…
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/ProtoSchemaConverterTest.java
  google-cloud-bigquerystorage/src/test/proto/test.proto
Labels: cla: yes

#436 fix: add missing resource name deps to v1beta1
  proto-google-cloud-bigquerystorage-v1beta1/pom.xml
Labels: cla: yes

#435 [CHANGE ME] Re-generated to pick up changes from googleapis.
  README.md
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/package-info.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClientTest.java
  proto-google-cloud-bigquerystorage-v1beta1/pom.xml
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ProjectName.java
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ReadSessionName.java
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/StreamName.java
  synth.metadata
Labels: cla: yes, context: partial

#429 refactor: Added Null checks for all object parameters for all public …
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BQTableSchemaToProtoDescriptor.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/DirectWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/SchemaCompatibility.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/WriterCache.java
Labels: automerge, cla: yes

#400 feat: Adding JsonToProtoMessage.java
  google-cloud-bigquerystorage/pom.xml
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/JsonToProtoMessage.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/JsonToProtoMessageTest.java
  google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
  pom.xml
Labels: automerge, cla: yes

#440 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#445 [CHANGE ME] Re-generated to pick up changes from self.
  README.md
  synth.metadata
Labels: cla: yes, context: none

#456 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: cla: yes, context: full
