Repository googleapis/java-bigquerystorage, pull requests merged in 2021-06, with the labels that each got.

#1106 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1107 chore: release gapic-generator-java v1.0.10
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryWriteClientTest.java
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1111 fix: call awaitTermination when close the stream writer
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterV2.java
Labels: api: bigquerystorage, cla: yes

#1116 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1119 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1123 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1125 chore: release gapic-generator-java v1.0.11
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/BaseBigQueryReadClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BaseBigQueryReadClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryWriteClientTest.java
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1128 fix: Make EOS Matching more robust
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/util/Errors.java
Labels: api: bigquerystorage, automerge, cla: yes

#1127 chore: release gapic-generator-java v1.0.12
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/BigQueryReadStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryReadStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryWriteStubSettings.java
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1132 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1134 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1137 chore: release gapic-generator-java v1.0.13
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ProjectName.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ReadSessionName.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ReadStreamName.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/TableName.java
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ProjectName.java
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/ReadSessionName.java
  proto-google-cloud-bigquerystorage-v1beta1/src/main/java/com/google/cloud/bigquery/storage/v1beta1/StreamName.java
  proto-google-cloud-bigquerystorage-v1beta2/src/main/java/com/google/cloud/bigquery/storage/v1beta2/ProjectName.java
  proto-google-cloud-bigquerystorage-v1beta2/src/main/java/com/google/cloud/bigquery/storage/v1beta2/ReadSessionName.java
  proto-google-cloud-bigquerystorage-v1beta2/src/main/java/com/google/cloud/bigquery/storage/v1beta2/ReadStreamName.java
  proto-google-cloud-bigquerystorage-v1beta2/src/main/java/com/google/cloud/bigquery/storage/v1beta2/TableName.java
  proto-google-cloud-bigquerystorage-v1beta2/src/main/java/com/google/cloud/bigquery/storage/v1beta2/WriteStreamName.java
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1138 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1139 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1141 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1142 fix: Add google-api-services-bigquery to google-cloud-bigquerystorage-bom
  google-cloud-bigquerystorage-bom/pom.xml
Labels: api: bigquerystorage, cla: yes

#1145 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1150 samples: indicate offset in append operation explicitly in a comment
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
Labels: api: bigquerystorage, automerge, cla: yes, samples

#1153 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1155 docs: user-provided streamOrTableName for default write streams
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
Labels: api: bigquerystorage, cla: yes

#1158 docs(sample): add IT for WriteToDefaultStream
  samples/snippets/src/test/java/com/example/bigquerystorage/WriteToDefaultStreamIT.java
Labels: api: bigquerystorage, cla: yes, samples

#1161 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes
