Repository googleapis/java-bigquerystorage, pull requests merged in 2021-01, with the labels that each got.

#760 fix: An extra test that is still calling old JsonStreamWriter append
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
Labels: api: bigquerystorage, cla: yes

#761 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#763 [CHANGE ME] Re-generated to pick up changes from self.
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: none

#767 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#769 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#771 chore: update gapic-generator-java to 0.0.18
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/BaseBigQueryReadClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/BigQueryReadStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/BigQueryReadStubSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/GrpcBigQueryReadCallableFactory.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BigQueryWriteClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/BigQueryWriteSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/stub/BigQueryWriteStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/stub/GrpcBigQueryWriteCallableFactory.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1alpha2/stub/GrpcBigQueryWriteStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/BigQueryStorageStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/GrpcBigQueryStorageCallableFactory.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/GrpcBigQueryStorageStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BaseBigQueryReadClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BaseBigQueryReadSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryWriteClient.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/BigQueryWriteSettings.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryReadStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryWriteStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/GrpcBigQueryReadCallableFactory.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/GrpcBigQueryReadStub.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/GrpcBigQueryWriteCallableFactory.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/GrpcBigQueryWriteStub.java
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#776 ci: wire in secret manager for samples ITs
  .kokoro/build.sh
  .kokoro/nightly/samples.cfg
  .kokoro/presubmit/samples.cfg
  synth.py
Labels: api: bigquerystorage, cla: yes, samples

#775 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#779 chore: fix nit
  synth.py
Labels: api: bigquerystorage, automerge, cla: yes

#784 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#791 fix: default stream integration test failures due to production expected change
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
Labels: api: bigquerystorage, automerge, cla: yes

#756 docs(samples): jsonstreamwriter samples
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WritePendingStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
  samples/snippets/src/test/java/com/example/bigquerystorage/WriteCommittedStreamIT.java
  samples/snippets/src/test/java/com/example/bigquerystorage/WritePendingStreamIT.java
  samples/snippets/src/test/java/com/example/bigquerystorage/WriteToDefaultStreamIT.java
Labels: api: bigquerystorage, cla: yes, samples

#790 deps: update protobuf
  pom.xml
Labels: api: bigquerystorage, automerge, cla: yes

#789 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#793 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#800 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#799 fix: StreamWriter hang when we reach the inflight limit control and is doing a retry
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1alpha2/StreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/StreamWriterTest.java
Labels: api: bigquerystorage, cla: yes

#805 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#811 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#814 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: bigquerystorage, automerge, cla: yes

#813 remove jackson dependency
  pom.xml
  renovate.json
Labels: api: bigquerystorage, cla: yes
