Repository googleapis/java-bigquerystorage, pull requests merged in 2021-07, with the labels that each got.

#1166 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1171 chore: remove distributionManagement section
  pom.xml
Labels: api: bigquerystorage, automerge, cla: yes

#1174 chore: remove distributionManagement section
  google-cloud-bigquerystorage-bom/pom.xml
Labels: api: bigquerystorage, automerge, cla: yes

#1177 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1181 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1183 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1180 feat: Expand bytes field type handling
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonToProtoMessage.java
Labels: api: bigquerystorage, cla: yes

#1185 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1188 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1194 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1198 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1199 chore: update renovate.json
  renovate.json
Labels: api: bigquerystorage, cla: yes

#1201 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1209 build: configure branch java7 as a release branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigquerystorage, automerge, cla: yes

#1212 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1210 feat: configure initial sp version
  .github/workflows/ci.yaml
Labels: api: bigquerystorage, automerge, cla: yes
