Repository googleapis/java-bigquerystorage, pull requests merged in 2021-05, with the labels that each got.

#1049 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: bigquerystorage, automerge, cla: yes

#1048 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: none

#1047 fix: remove schema update capability from jsonwriter and delete related tests
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/OnSchemaUpdateRunnable.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
Labels: api: bigquerystorage, cla: yes

#1055 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1056 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1057 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1060 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1058 fix: migrate json writer to use StreamWriterV2
  google-cloud-bigquerystorage/clirr-ignored-differences.xml
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/JsonStreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryBigDecimalByteStringEncoderTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryTimeEncoderTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta2/it/ITBigQueryWriteManualClientTest.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
Labels: api: bigquerystorage, cla: yes

#1066 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1070 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1071 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1074 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1077 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1076 [CHANGE ME] Re-generated to pick up changes from googleapis.
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClient.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1beta1/BaseBigQueryStorageClientTest.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ArrowProto.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ArrowSerializationOptions.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ReadSession.java
  proto-google-cloud-bigquerystorage-v1/src/main/java/com/google/cloud/bigquery/storage/v1/ReadSessionOrBuilder.java
  proto-google-cloud-bigquerystorage-v1/src/main/proto/google/cloud/bigquery/storage/v1/arrow.proto
  proto-google-cloud-bigquerystorage-v1/src/main/proto/google/cloud/bigquery/storage/v1/storage.proto
  proto-google-cloud-bigquerystorage-v1/src/main/proto/google/cloud/bigquery/storage/v1/stream.proto
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1081 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1089 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1092 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: bigquerystorage, automerge, cla: yes, context: full

#1094 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1096 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1099 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: bigquerystorage, automerge, cla: yes

#1101 fix!: remove default deadline for AppendRows API
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/BigQueryWriteStubSettings.java
  synth.metadata
Labels: api: bigquerystorage, cla: yes, context: full

#1102 fix: More robust STREAM_RST logic
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/util/Errors.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta1/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2/stub/readrows/ApiResultRetryAlgorithm.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/util/ErrorsTest.java
Labels: api: bigquerystorage, cla: yes
