Repository googleapis/java-bigquerystorage, pull requests merged in 2022-01, with the labels that each got.

#1471 docs(samples): add finalize call to our samples
  README.md
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteBufferedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
Labels: automerge, api: bigquerystorage, samples

#1477 chore: change name to api_shortname in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: bigquerystorage, owlbot:ignore

#1485 chore: update release-level in .repo-metadata.json
  .repo-metadata.json
Labels: automerge, api: bigquerystorage, owlbot:ignore

#1488 fix(java): add reflection configuration for native-image testing
  google-cloud-bigquerystorage/src/test/resources/META-INF/native-image/reflect-config.json
Labels: api: bigquerystorage

#1489 docs(samples): update to v1 in doc URls
  samples/snippets/src/main/java/com/example/bigquerystorage/ParallelWriteCommittedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteBufferedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WritePendingStream.java
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteToDefaultStream.java
Labels: automerge, api: bigquerystorage, samples

#1490 deps: exclude un-used runtime dependencies brought in by gax-grpc
  google-cloud-bigquerystorage/pom.xml
Labels: automerge, api: bigquerystorage

#1498 docs(tutorials): add new tutorials directory and JsonWriterDefaultStream tutorial
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  .github/workflows/ci.yaml
  .github/workflows/samples.yaml
  owlbot.py
  tutorials/JsonWriterDefaultStream/JsonWriterDefaultStream.java
  tutorials/JsonWriterDefaultStream/pom.xml
Labels: api: bigquerystorage

#1501 deps: upgrade google-cloud-shared-dependencies to v2.7.0
  pom.xml
Labels: kokoro:force-run, automerge, api: bigquerystorage

#1500 docs(tutorials): add a README.md
  tutorials/README.md
Labels: automerge, api: bigquerystorage
