Repository googleapis/java-bigquerystorage, pull requests merged in 2022-04, with the labels that each got.

#1607 fix: even better ISO compilance
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessage.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonToProtoMessageTest.java
  google-cloud-bigquerystorage/src/test/proto/jsonTest.proto
Labels: api: bigquerystorage

#1616 chore(docs): updating .repo-metadata for library_type
  .repo-metadata.json
Labels: automerge, api: bigquerystorage, size: xs

#1625 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: api: bigquerystorage, size: m

#1624 feat: next release from main branch is 2.12.2
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: automerge, api: bigquerystorage, size: s

#1628 docs(samples): update WriteComittedStream sample code to match best practices
  samples/snippets/src/main/java/com/example/bigquerystorage/WriteCommittedStream.java
Labels: api: bigquerystorage, samples, size: m
