Repository googleapis/java-bigquerystorage, pull requests merged in 2023-11, with the labels that each got.

#2208 chore: setup 2.38.x lts branch
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: bigquerystorage, size: s

#2309 fix: add comment/documentation for setRetrySettings
  README.md
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
Labels: api: bigquerystorage, size: s

#2275 feat: Add integration tests with RetrySettings enabled.
  .kokoro/build.sh
  README.md
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPoolTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteNonQuotaRetryTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteQuotaRetryTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/WriteRetryTestUtil.java
Labels: api: bigquerystorage, samples, size: l

#2209 ci: configure the protected branch
  .github/workflows/ci.yaml
Labels: automerge, api: bigquerystorage, size: m

#2324 chore: fix retry-quota jobs
  .kokoro/build.sh
  README.md
Labels: api: bigquerystorage, size: xs

#2325 chore: fix retry-quota jobs
  .kokoro/build.sh
Labels: automerge, api: bigquerystorage, size: xs

#2327 chore: fix graalvm kokoro builds
  .kokoro/build.sh
  .kokoro/presubmit/graalvm-native-17.cfg
  .kokoro/presubmit/graalvm-native.cfg
  owlbot.py
Labels: api: bigquerystorage, size: m

#2330 fix: an attempt to solve test failure in nightly build
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java
Labels: api: bigquerystorage, size: s

#2333 fix: fix the write api integration test
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/ConnectionWorkerPoolTest.java
Labels: api: bigquerystorage, size: s

#2329 chore: add -U and -C to mvn install
  .kokoro/build.sh
Labels: automerge, api: bigquerystorage, size: s
