Repository googleapis/java-bigquerystorage, pull requests merged in 2023-12, with the labels that each got.

#2346 chore: update build.sh to run graalvm checks as verify
  .kokoro/build.sh
  README.md
Labels: automerge, api: bigquerystorage, size: s

#2347 chore: fix graalvm builds
  .gitignore
  .kokoro/build.sh
  pom.xml
Labels: automerge, api: bigquerystorage, size: m

#2358 feat: Exponentially backoff on INTERNAL errors for Default streams
  README.md
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/ConnectionWorker.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteNonQuotaRetryTest.java
Labels: api: bigquerystorage, size: m
