Repository googleapis/java-bigquerystorage, pull requests merged in 2024-09, with the labels that each got.

#2628 chore: remove unused image tag in .OwlBot-hermetic.yaml
  .github/.OwlBot-hermetic.yaml
Labels: api: bigquerystorage, size: xs

#2636 chore: restore documentation for OpenTelemetry
  README.md
Labels: api: bigquerystorage, size: m

#2642 chore: Add Clirr exemptions for Protobuf 4.27.4+ runtime
  proto-google-cloud-bigquerystorage-v1/clirr-ignored-differences.xml
  proto-google-cloud-bigquerystorage-v1alpha/clirr-ignored-differences.xml
  proto-google-cloud-bigquerystorage-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-bigquerystorage-v1beta2/clirr-ignored-differences.xml
Labels: api: bigquerystorage, size: m

#2587 fix: Persist missingValueInterpretationMap in StreamWriter's Builder
  google-cloud-bigquerystorage/clirr-ignored-differences.xml
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/SchemaAwareStreamWriter.java
  google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1/StreamWriter.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/JsonStreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/StreamWriterTest.java
  google-cloud-bigquerystorage/src/test/java/com/google/cloud/bigquery/storage/v1/it/ITBigQueryWriteManualClientTest.java
Labels: api: bigquerystorage, size: l

#2664 chore: use composite action
  .github/scripts/hermetic_library_generation.sh
  .github/workflows/hermetic_library_generation.yaml
Labels: api: bigquerystorage, size: m
